version: '2'
services:
 front-end:
   build: ./front-end
   volumes:
     - ./front-end:/app
   environment:
     - PORT=3000
     - HOST=0.0.0.0
   tty: true
 back-end:
   build: ./back-end
   restart: always
   volumes:
     - ./back-end:/app
   tty: true
   depends_on:
     - pg
 proxy:
   image: nginx:1.12.2
   restart: always
   command: /bin/sh -c "envsubst < /etc/nginx/conf.d/proxy.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
   volumes:
     - ./proxy/nginx.conf:/etc/nginx/conf.d/proxy.template
   environment:
     - FRONTEND_URL=http://front-end:3000
     - BACKEND_URL=http://back-end:3001
   ports:
     - 80:80
   depends_on:
     - back-end
     - front-end
   tty: true
 pg:
   image: postgres:11
   restart: always
   ports:
      - 5432:5432
   volumes:
     - ./pg/lancement.sh:/docker-entrypoint-initdb.d/lancement.sh
     - ./pg/scripts:/docker-entrypoint-initdb.d/scripts
