version: '2'
services:
  front-end:
    build: ./front-end
    volumes:
      - ./front-end:/app
    environment:
      - PROXY_URL=http://proxy
      - PORT=3000
      - HOST=0.0.0.0
      - DEBUG=srav-frontend:*
    tty: true
  back-end:
    build: ./back-end
    restart: always
    volumes:
      - ./back-end:/app
    tty: true
    depends_on:
      - pg
    environment:
      - MAIL_URL=http://mail-server:3000
      - DEBUG=srav-backend:*
  mail-server:
    build: ./mail-server
    restart: always
    volumes:
      - ./mail-server:/app
    environment:
      - PORT=3000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=smtp.synaltic@gmail.com
      - SMTP_PASSWORD=PGctP9Fs4E959Goc
      - PROXY_USER=rverdier@synaltic.fr
      - DEBUG=mail-server:info:*
      - API_MANAGER_URL=http://nginx/api-manager
      - APP_URL=http://mail-server:3000
    tty: true
  proxy:
    image: nginx:1.12.2
    restart: always
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/proxy.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/proxy.template
    environment:
      - FRONTEND_URL=http://front-end:3000
      - BACKEND_URL=http://back-end:3001
    ports:
      - 80:80
    depends_on:
      - back-end
      - front-end
    tty: true
  pg:
    image: postgres:11.6
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pg/lancement.sh:/docker-entrypoint-initdb.d/lancement.sh
      - ./pg/scripts:/docker-entrypoint-initdb.d/scripts
