apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuYXBwLnN5bmFsdGljLmV1Ijp7InVzZXJuYW1lIjoic3luYWx0aWMiLCJwYXNzd29yZCI6IndkS1lSeEZKMmM2ZnNxIiwiZW1haWwiOiJpbmZyYUBzeW5hbHRpYy5mciIsImF1dGgiOiJjM2x1WVd4MGFXTTZkMlJMV1ZKNFJrb3lZelptYzNFPSJ9fX0=
kind: Secret
metadata:
  namespace: srav
  name: regcred

type: kubernetes.io/dockerconfigjson
